### ISSUE TITLE
Update and complete database implementation

### ISSUE THREAD

**Issue by CptMikhailov** [CptMikhailov/SidewaysT#1]
~~For the little amount of data this project supports, moving to a lightweight, single file NoSQL solution will work better.~~

Edit: I've decided to not continue with using a document database, instead, two solutions will be created using SQL Server 17. There will be the traditional relational model, and will also experiment with using SQL Server's graph database functions. These two models will be tested, and the one that proves the cleanest, simplest, and fastest approach will be used going forward.

List of tasks:
- [ ] #3: Complete relational database model
- [ ] #4: Implement SQL graph
- [ ] #5: Thoroughly test both methodologies to determine best course of action.
